// <auto-generated />
using System;
using DailyManagment;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyManagment.Migrations
{
    [DbContext(typeof(DailyContext))]
    [Migration("20231016164612_CreateTableDailies")]
    partial class CreateTableDailies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("DailyManagment.Models.Daily", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnaliseCredito")
                        .HasColumnType("TEXT");

                    b.Property<string>("CRM")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cliente")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDefinicao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataEntregaPrevista")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataEntregaReal")
                        .HasColumnType("TEXT");

                    b.Property<string>("PV")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pendencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Projeto_Aplicacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsavel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rev")
                        .HasColumnType("TEXT");

                    b.Property<string>("Segmento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Dailies");
                });
#pragma warning restore 612, 618
        }
    }
}
